services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - findle-network
    depends_on:
      - backend
    env_file:
      - ./frontend/.env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - findle-network
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./backend/.env

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - findle-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: findle_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d findle_db"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  findle-network:
    driver: bridge

volumes:
  postgres_data:
