apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: findle
  labels:
    app: backend
    app.kubernetes.io/part-of: findle
data:
  ALGORITHM: HS256
  ACCESS_TOKEN_EXPIRE_MINUTES: "1440"
  FIRST_SUPERUSER_USERNAME: admin
  FIRST_SUPERUSER_EMAIL: admin@findle.local
  SEED_DATA: "true"
