apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: findle
  labels:
    app: backend
    app.kubernetes.io/part-of: findle
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
