apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  namespace: findle
  labels:
    app: mongodb
    app.kubernetes.io/part-of: findle
data:
  MONGODB_DB: findle_db
  MONGODB_REPLICA_SET: rs0
